Fix compiler error
```
Compiling 1 file (.ex)
    error: recursive variable definition in patterns:

    create(direction, {x, y} = {x, y} = position)

    the variable "x" is defined in function of itself
    │
 33 │   def create(direction, {x, y} = {x, y} = position)
    │       ^
    │
    └─ lib/robot_simulator.ex:33:7: RobotSimulator.create/2

== Compilation error in file lib/robot_simulator.ex ==
** (CompileError) lib/robot_simulator.ex: cannot compile module RobotSimulator (errors have been logged)
    (stdlib 7.1) maps.erl:894: :maps.fold_1/4
    lib/robot_simulator.ex:33: (module)
```